application:
    name: my-application
    version: 1.0.0
database:
    url: jdbc:mysql://localhost:3306/WF-INIT-TRADE
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8080
    servlet:
        context-path: /
swaager:
    enabled: true